# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 13:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('api_key', models.CharField(max_length=50)),
                ('cron_time', models.TimeField(blank=True)),
                ('sync_tag', models.CharField(blank=True, default='', max_length=50)),
                ('django_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('priority', models.FloatField(default=1)),
                ('value', models.FloatField(default=1.0)),
                ('attribute', models.CharField(default='str', max_length=3)),
                ('repeat_days', models.CharField(blank=True, max_length=50)),
                ('everyX', models.IntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='DailyChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('daily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='sync_accounts.Daily')),
            ],
        ),
        migrations.CreateModel(
            name='DailyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=0)),
                ('value', models.FloatField(default=1)),
                ('daily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='sync_accounts.Daily')),
            ],
        ),
        migrations.CreateModel(
            name='DailyId',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_ids', to='sync_accounts.Account')),
                ('daily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ids', to='sync_accounts.Daily')),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('good', models.BooleanField(default=True)),
                ('bad', models.BooleanField(default=False)),
                ('priority', models.FloatField(default=1)),
                ('value', models.FloatField(default=1.0)),
                ('attribute', models.CharField(default='str', max_length=3)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='HabitHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=0)),
                ('value', models.FloatField(default=1)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='sync_accounts.Habit')),
            ],
        ),
        migrations.CreateModel(
            name='HabitId',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_ids', to='sync_accounts.Account')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ids', to='sync_accounts.Habit')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('priority', models.FloatField(default=1)),
                ('value', models.FloatField(default=1.0)),
                ('attribute', models.CharField(default='str', max_length=3)),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='TodoChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='sync_accounts.Todo')),
            ],
        ),
        migrations.CreateModel(
            name='TodoId',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_ids', to='sync_accounts.Account')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ids', to='sync_accounts.Todo')),
            ],
        ),
    ]
