# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cron_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='sync_tag',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='daily',
            name='attribute',
            field=models.CharField(default='str', max_length=3),
        ),
        migrations.AlterField(
            model_name='daily',
            name='everyX',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='daily',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='priority',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='daily',
            name='repeat_days',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='daily',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='value',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='habit',
            name='attribute',
            field=models.CharField(default='str', max_length=3),
        ),
        migrations.AlterField(
            model_name='habit',
            name='bad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habit',
            name='good',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='priority',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='habit',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='value',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='todo',
            name='attribute',
            field=models.CharField(default='str', max_length=3),
        ),
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='value',
            field=models.FloatField(default=1.0),
        ),
    ]
