# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='repeat_days',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
