# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync_accounts', '0002_auto_20160817_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailychecklistitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyid',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='daily_ids', to='sync_accounts.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitid',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='habit_ids', to='sync_accounts.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todochecklistitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoid',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='todo_ids', to='sync_accounts.Account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyid',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='habitid',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todoid',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
