# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 12:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_accounts', '0003_auto_20160817_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
