# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 13:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync_accounts', '0004_todo_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('value', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='HabitHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('value', models.FloatField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='daily',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='habit',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='habithistory',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='sync_accounts.Habit'),
        ),
        migrations.AddField(
            model_name='dailyhistory',
            name='daily',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='sync_accounts.Daily'),
        ),
    ]
