# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_accounts', '0005_auto_20160818_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhistory',
            name='date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habithistory',
            name='date',
            field=models.IntegerField(default=0),
        ),
    ]
