# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_accounts', '0006_auto_20160818_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
