# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 08:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.models import User
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sync_accounts', '0007_daily_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='django_user',
            field=models.ForeignKey(default=User.objects.all()[0].pk,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='accounts',
                                    to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
